from collections.abc import Mapping, Sequence

from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class PlanPass(ComponentRef): ...

class KvCacheEviction(PlanPass):
    descriptor: ComponentDescriptor
    def __init__(
        self,
        *,
        implementation: str = "pllm/importance-kv-cache-eviction/v1",
        observation_window: tuple[int, int] | Mapping[str, int] = (1, 5),
        static_keep: tuple[int, int] | Mapping[str, int] = (3, 10),
        dynamic_keep: tuple[int, int] | Mapping[str, int] = (1, 4),
        alpha: tuple[int, int] | Mapping[str, int] = (3, 5),
        cluster_sizes: Sequence[int] = (32, 16),
        share_adjacent_layers: bool = True,
    ) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class AtlasApproximationSearch(PendingMethod): ...
class EncformerRepresentationAssignment(PendingMethod): ...
class FuseFssPredicateFusion(PendingMethod): ...
class RosettaCkksTfheAssignment(PendingMethod): ...
class BreakingLayerBarrierAssignment(PendingMethod): ...
class CipherPruneTokenPruning(PendingMethod): ...
class RedashGarbledScaling(PendingMethod): ...
class DittoQuantizationAwareTransform(PendingMethod): ...
class MpcMinimizedClientServerPartition(PendingMethod): ...
class MpcFormerDistillation(PendingMethod): ...
class HyccHybridProtocolAssignment(PendingMethod): ...
class FevBddDecisionDiagramFactoring(PendingMethod): ...
class AtlasApproximationBudget(PendingMethod): ...
class BifrostEncryptedStagePlacement(PendingMethod): ...
class ShaftFixedPointSchedule(PendingMethod): ...
class CompactDistributionCalibration(PendingMethod): ...
class CipherPruneQualityBound(PendingMethod): ...
class BatchedIntervalComparisonSchedule(PendingMethod): ...
class HyccConversionCostPlanner(PendingMethod): ...
class MpcMinimizedPrivacyPlacement(PendingMethod): ...
