from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class KernelBackend(ComponentRef): ...

class Cpu(KernelBackend):
    descriptor: ComponentDescriptor
    def __init__(self, *, threads: int = 1) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class AppleMetal(KernelBackend):
    descriptor: ComponentDescriptor
    def __init__(self, *, min_rows: int = 8) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class SecureGpuBackend(PendingMethod): ...
class PiranhaMultiPartyGpuDispatch(PendingMethod): ...
class OrcaFssGpuKernels(PendingMethod): ...
