from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class QuantizationScheme(ComponentRef): ...

class SymmetricPerRow(QuantizationScheme):
    descriptor: ComponentDescriptor
    def __init__(self, *, weight_bits: int = 8, activation_bits: int = 8) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class DittoPrivateQuantization(PendingMethod): ...
