from collections.abc import Iterable, Mapping
from typing import Any

class SourceRecord:
    def __init__(self, _canonical_bytes: bytes) -> None: ...
    @classmethod
    def from_dict(cls, document: Mapping[str, Any]) -> SourceRecord: ...
    @property
    def id(self) -> str: ...
    @property
    def digest(self) -> str: ...
    def canonical_bytes(self) -> bytes: ...
    def to_dict(self) -> dict[str, Any]: ...

class MethodRecord:
    def __init__(self, _canonical_bytes: bytes) -> None: ...
    @classmethod
    def from_dict(cls, document: Mapping[str, Any]) -> MethodRecord: ...
    @property
    def id(self) -> str: ...
    @property
    def digest(self) -> str: ...
    def canonical_bytes(self) -> bytes: ...
    def to_dict(self) -> dict[str, Any]: ...

class ArtifactLock:
    id: str
    source_record_id: str
    revision: str
    artifact_digest: str | None
    license_review: str
    isolation: str
    repository_url: str | None
    status: str
    evidence_digest: str | None
    def __init__(
        self,
        id: str,
        source_record_id: str,
        revision: str,
        artifact_digest: str | None,
        license_review: str,
        isolation: str,
        repository_url: str | None = None,
        status: str = "quarantined",
        evidence_digest: str | None = None,
    ) -> None: ...
    @property
    def digest(self) -> str: ...
    def canonical_bytes(self) -> bytes: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, document: Mapping[str, Any]) -> ArtifactLock: ...
    def lock_artifact(self, *, artifact_digest: str) -> ArtifactLock: ...
    def verify(self, *, evidence_digest: str) -> ArtifactLock: ...
    def reject(self, *, evidence_digest: str) -> ArtifactLock: ...

class PromotionDecision:
    method_id: str
    eligible: bool
    blockers: tuple[str, ...]

class ResearchRegistry:
    def __init__(
        self,
        *,
        sources: Iterable[SourceRecord] = ...,
        methods: Iterable[MethodRecord] = ...,
        artifacts: Iterable[ArtifactLock] = ...,
    ) -> None: ...
    def sources(self) -> tuple[SourceRecord, ...]: ...
    def methods(self) -> tuple[MethodRecord, ...]: ...
    def artifacts(self) -> tuple[ArtifactLock, ...]: ...
    def source(self, identity: str) -> SourceRecord: ...
    def method(self, identity: str) -> MethodRecord: ...
    def artifact(self, identity: str) -> ArtifactLock: ...
    def promotion(self, method_id: str) -> PromotionDecision: ...
