from typing import Any, Mapping

class ResearchMetadataError(ValueError): ...
class ResearchMetadataIOError(OSError): ...

class PublicationAssessment:
    @property
    def data(self) -> Mapping[str, Any]: ...
    @property
    def decision(self) -> str: ...
    @property
    def digest(self) -> str: ...
    def canonical_bytes(self) -> bytes: ...
    def to_dict(self) -> dict[str, Any]: ...

class SourceRecord:
    @property
    def payload(self) -> Mapping[str, Any]: ...
    @property
    def aliases(self) -> tuple[str, ...]: ...
    @property
    def identifier(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class MethodRecord:
    @property
    def payload(self) -> Mapping[str, Any]: ...
    @property
    def aliases(self) -> tuple[str, ...]: ...
    @property
    def identifier(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class RecipeRecord:
    @property
    def payload(self) -> Mapping[str, Any]: ...
    @property
    def aliases(self) -> tuple[str, ...]: ...
    @property
    def identifier(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

def list_sources() -> tuple[SourceRecord, ...]: ...
def list_methods() -> tuple[MethodRecord, ...]: ...
def list_recipes() -> tuple[RecipeRecord, ...]: ...
def get_source(identity: str) -> SourceRecord: ...
def get_method(identity: str) -> MethodRecord: ...
def get_recipe(identity: str) -> RecipeRecord: ...
def assess_publication(request: Mapping[str, Any] | bytes | str) -> PublicationAssessment: ...
def render_agents_guide() -> str: ...
