from pllm.configuration import ComponentDescriptor, ComponentRef

class NonlinearProtocol(ComponentRef): ...

class BinaryTableGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class R03CrtGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
