from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class NonlinearProtocol(ComponentRef): ...

class ArithmeticGarblingSiluQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class BinaryTableGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class R03CrtGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ShaftFixedPointTransformerOps(PendingMethod): ...
class CompactPiecewiseActivation(PendingMethod): ...
class CurlWaveletEncodedTable(PendingMethod): ...
class LlamaSecureMath(PendingMethod): ...
class SirnnSecureMath(PendingMethod): ...
class WaveletHomomorphicLookup(PendingMethod): ...
