from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod
from pllm._native import CompactQ7Reference, ScaledSiluQ7Reference

class NonlinearProtocol(ComponentRef): ...

class ArithmeticGarblingSiluQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class BinaryTableGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class R03CrtGatedMultiplyQ7(NonlinearProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ShaftFixedPointTransformerOps(PendingMethod): ...
class CompactPiecewiseActivation(PendingMethod): ...
class CurlWaveletEncodedTable(PendingMethod): ...
class LlamaSecureMath(PendingMethod): ...
class SirnnSecureMath(PendingMethod): ...
class WaveletHomomorphicLookup(PendingMethod): ...
class CompactPrivateIntervalSelection(PendingMethod): ...
class CurlProbabilisticTruncation(PendingMethod): ...
class LlamaBoundedMathOperators(PendingMethod): ...
class BumbleBeeSharedNonlinear(PendingMethod): ...
class FuseFssNonlinearOperator(PendingMethod): ...
class SigmaSharedNonlinear(PendingMethod): ...
class LogRowPrivateRowIndex(PendingMethod): ...
class ScaleQuantConversion(PendingMethod): ...
class MpcFormerActivationApproximation(PendingMethod): ...
class CryptFlowExactTruncation(PendingMethod): ...
class FssFixedPointTruncation(PendingMethod): ...

def fit_compact_silu_q7_reference(
    public_calibration_counts: bytes, max_pieces: int = 4
) -> CompactQ7Reference: ...
def create_logrow_scaled_silu_q7_reference(max_abs: int) -> ScaledSiluQ7Reference: ...
