from collections.abc import Mapping
from typing import Any

from pllm.configuration import ComponentDescriptor as ComponentDescriptor
from pllm.configuration import ComponentRef as ComponentRef

def list_component_classes() -> tuple[type[ComponentRef], ...]: ...
def list_components() -> tuple[ComponentDescriptor, ...]: ...
def get(identity: str) -> type[ComponentRef]: ...
def get_component(identity: str) -> ComponentDescriptor: ...
def create_component(identity: str, params: Mapping[str, Any]) -> ComponentRef: ...
