//! Strict bounded records for offline network placement admission.
//! Offers and operator IDs are declarations, not authentication or evidence of
//! physical independence. Resource requirements are caller-supplied estimates
//! constrained by native owned-tensor byte floors, not peak-RAM certificates.

use crate::Digest;
use serde::{de, Deserialize, Deserializer, Serialize};
use std::collections::BTreeMap;
use std::fmt;
use std::marker::PhantomData;

pub const NETWORK_PLACEMENT_SCHEMA: &str = "pllm.network_placement.v1";
pub const NETWORK_PLACEMENT_REQUIREMENTS_SCHEMA: &str = "pllm.network_placement_requirements.v1";
pub const NETWORK_PLACEMENT_DIGEST_DOMAIN: &str = "pllm.network_placement.validated.v1";
pub const NETWORK_MAX_DOCUMENT_BYTES: usize = 1024 * 1024;
pub const NETWORK_MAX_MODEL_PLAN_BYTES: usize = 16 * 1024 * 1024;
pub const NETWORK_MAX_ROLES: usize = 16;
pub const NETWORK_MAX_PARTIES: usize = 64;
pub const NETWORK_MAX_ALLOWED_MODELS: usize = 64;
pub const NETWORK_CAPABILITIES: &[&str] = &[
    "trusted_client",
    "masked_linear_provider",
    "trusted_preparation",
    "public_linear_provider",
];

/// Explicit experiment.v3 network intent. It has no local filesystem root.
/// The optional snapshot lock is an explicit null when planning from live offers.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkExperimentDeployment {
    pub network_id: String,
    #[serde(deserialize_with = "nonzero_digest")]
    pub network_spec_digest: Digest,
    #[serde(deserialize_with = "optional_nonzero_digest")]
    pub snapshot_digest: Option<Digest>,
}

fn optional_nonzero_digest<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Digest>, D::Error> {
    let value = Option::<Digest>::deserialize(d)?;
    if value
        .as_ref()
        .is_some_and(|digest| digest.as_str().bytes().all(|byte| byte == b'0'))
    {
        return Err(de::Error::custom("network digest must be nonzero"));
    }
    Ok(value)
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkRoleAssignment {
    pub role_id: String,
    pub party_id: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct NetworkRoleRequirement {
    pub role_id: String,
    pub capability: String,
}

/// Assignment-free requirements generated by complete native admission only.
/// Roles and separation pairs are identity-sorted and bounded by native topology.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct NetworkPlacementRequirements {
    pub schema: String,
    pub roles: Vec<NetworkRoleRequirement>,
    /// Operator ownership declarations; not proof of physical independence.
    pub separate_operators: Vec<[String; 2]>,
    /// One byte per owned tensor element, excluding copies/scales/peak memory.
    pub minimum_weight_bytes: BTreeMap<String, u64>,
    pub minimum_memory_bytes: BTreeMap<String, u64>,
    pub schedule_digest: Digest,
    pub model_plan_digest: Digest,
    pub composition_digest: Digest,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkPartyOffer {
    pub party_id: String,
    pub operator_id: String,
    #[serde(deserialize_with = "nonzero_digest")]
    pub instance_epoch: Digest,
    pub expires_at_ms: u64,
    #[serde(deserialize_with = "capabilities")]
    pub capabilities: Vec<String>,
    pub max_memory_bytes: u64,
    pub max_weight_bytes: u64,
    pub max_sessions: u32,
    pub active_sessions: u32,
    /// Exact decoder config digests, or `*`. Checkpoint names are not admitted.
    #[serde(deserialize_with = "allowed_models")]
    pub allowed_models: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkPlacementRequest {
    pub schema: String,
    #[serde(deserialize_with = "nonzero_digest")]
    pub snapshot_digest: Digest,
    pub evaluated_at_ms: u64,
    pub client_party_id: String,
    #[serde(deserialize_with = "roles")]
    pub roles: Vec<NetworkRoleAssignment>,
    #[serde(deserialize_with = "parties")]
    pub parties: Vec<NetworkPartyOffer>,
    #[serde(deserialize_with = "requirements")]
    pub required_memory_bytes: BTreeMap<String, u64>,
    #[serde(deserialize_with = "requirements")]
    pub required_weight_bytes: BTreeMap<String, u64>,
}

/// Output retains request fields; placement_digest commits to all other fields.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ValidatedNetworkPlacement {
    #[serde(flatten)]
    pub request: NetworkPlacementRequest,
    pub schedule_digest: Digest,
    pub model_plan_digest: Digest,
    pub composition_digest: Digest,
    /// Per-role owned tensor elements at one byte each, deduplicated by native
    /// artifact ID across both phases. Excludes scales, float source storage,
    /// native copies, working buffers and peak memory.
    pub minimum_weight_bytes: BTreeMap<String, u64>,
    /// Owned-weight resident lower bound only; currently equals weight floor.
    pub minimum_memory_bytes: BTreeMap<String, u64>,
    pub placement_digest: Digest,
}

fn nonzero_digest<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Digest, D::Error> {
    let digest = Digest::deserialize(deserializer)?;
    if digest.as_str().bytes().all(|byte| byte == b'0') {
        return Err(de::Error::custom("network digest must be nonzero"));
    }
    Ok(digest)
}

fn bounded_vec<'de, D, T, const MAX: usize>(deserializer: D) -> Result<Vec<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    struct Visitor<T, const MAX: usize>(PhantomData<T>);
    impl<'de, T: Deserialize<'de>, const MAX: usize> de::Visitor<'de> for Visitor<T, MAX> {
        type Value = Vec<T>;
        fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "an array with at most {MAX} records")
        }
        fn visit_seq<A: de::SeqAccess<'de>>(self, mut seq: A) -> Result<Self::Value, A::Error> {
            let mut output = Vec::new();
            while let Some(item) = seq.next_element()? {
                if output.len() == MAX {
                    return Err(de::Error::custom("network array exceeds its record bound"));
                }
                output.push(item);
            }
            Ok(output)
        }
    }
    deserializer.deserialize_seq(Visitor::<T, MAX>(PhantomData))
}

fn roles<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<NetworkRoleAssignment>, D::Error> {
    bounded_vec::<_, _, NETWORK_MAX_ROLES>(d)
}
fn parties<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<NetworkPartyOffer>, D::Error> {
    bounded_vec::<_, _, NETWORK_MAX_PARTIES>(d)
}
fn capabilities<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<String>, D::Error> {
    bounded_vec::<_, _, 4>(d)
}
fn allowed_models<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<String>, D::Error> {
    bounded_vec::<_, _, NETWORK_MAX_ALLOWED_MODELS>(d)
}

fn requirements<'de, D: Deserializer<'de>>(d: D) -> Result<BTreeMap<String, u64>, D::Error> {
    struct Visitor;
    impl<'de> de::Visitor<'de> for Visitor {
        type Value = BTreeMap<String, u64>;
        fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(
                f,
                "a map of at most {NETWORK_MAX_ROLES} distinct role requirements"
            )
        }
        fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<Self::Value, A::Error> {
            let mut output = BTreeMap::new();
            while let Some((key, value)) = map.next_entry::<String, u64>()? {
                if output.len() == NETWORK_MAX_ROLES || output.insert(key, value).is_some() {
                    return Err(de::Error::custom(
                        "duplicate or excessive network requirements",
                    ));
                }
            }
            Ok(output)
        }
    }
    d.deserialize_map(Visitor)
}
