from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod
from pllm.state.public_prefix import PublicPrefixCapsule as PublicPrefixCapsule

class StateProtocol(ComponentRef): ...

class ClientLocalKv(StateProtocol):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ClientPrefixReuse(ComponentRef):
    descriptor: ComponentDescriptor
    def __init__(self, *, max_bytes: int, fixed_input_tokens: int) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class EncryptedKvState(PendingMethod): ...
class ProtectedKvSelection(PendingMethod): ...
class SpeculativePrivateDecode(PendingMethod): ...
class SirnnFixedPointSequence(PendingMethod): ...
class CipherGptGenerationState(PendingMethod): ...
class PumaSharedKvState(PendingMethod): ...
class Aby2ResidentShares(PendingMethod): ...
class MpcachePrivateDynamicGather(PendingMethod): ...
