from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class CorrelationSource(ComponentRef): ...

class SeededExpansion(CorrelationSource):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class SecretReplicationPcf(PendingMethod): ...
class FiniteFieldPcg(PendingMethod): ...
class RingPcg(PendingMethod): ...
class SparseUnitVectorCorrelation(PendingMethod): ...
class RingVectorOle(PendingMethod): ...
class RingLpnPcg(PendingMethod): ...
class SilentOtExtension(PendingMethod): ...
class CompressedVectorOle(PendingMethod): ...
class SecretReplicationKeySetup(PendingMethod): ...
class FiniteFieldPcgOle(PendingMethod): ...
class RingPcgOle(PendingMethod): ...
class SparseUnitExpansion(PendingMethod): ...
class RingLpnParameterPolicy(PendingMethod): ...
class OneUseSilentOtMaterial(PendingMethod): ...
class CompressedVoleExpansion(PendingMethod): ...
class MaverickPrivateMaskIssuance(PendingMethod): ...
class SecretDualCodeSetup(PendingMethod): ...
class TrapdooredMatrixKeySetup(PendingMethod): ...
class FastQueryTableSharing(PendingMethod): ...
class SigmaDealerFssKeys(PendingMethod): ...
class FluteLookupKeys(PendingMethod): ...
class GrottoHelperDpfKeys(PendingMethod): ...
class SilentNiscOtExtension(PendingMethod): ...
