from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.components._planned import PendingComponent as PendingMethod

class CorrelationSource(ComponentRef): ...

class SeededExpansion(CorrelationSource):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class SecretReplicationPcf(PendingMethod): ...
class FiniteFieldPcg(PendingMethod): ...
class RingPcg(PendingMethod): ...
class SparseUnitVectorCorrelation(PendingMethod): ...
class RingVectorOle(PendingMethod): ...
class RingLpnPcg(PendingMethod): ...
class SilentOtExtension(PendingMethod): ...
class CompressedVectorOle(PendingMethod): ...
