from typing import Any, Never, final

class Matrix:
    def __init__(self, data: bytes, rows: int, cols: int) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def weight_bytes(self) -> int: ...

@final
class CompiledPlan:
    def __new__(cls) -> Never: ...
    @property
    def logical_plan(self) -> bytes: ...
    @property
    def execution_plan(self) -> bytes: ...
    @property
    def plan_lock(self) -> bytes: ...
    @property
    def region_program(self) -> bytes: ...
    @property
    def configuration_digest(self) -> str: ...
    @property
    def logical_plan_digest(self) -> str: ...
    @property
    def execution_plan_digest(self) -> str: ...
    @property
    def plan_lock_digest(self) -> str: ...
    @property
    def input_shape(self) -> tuple[int, ...]: ...
    @property
    def output_shape(self) -> tuple[int, ...]: ...
    def execute_wrap32(
        self,
        weights: bytes,
        input: bytes,
        threads: int = 1,
        simd: bool = True,
    ) -> bytes: ...
    def benchmark_wrap32(
        self,
        weights: bytes,
        input: bytes,
        benchmark_id: str,
        privacy_cohort: str,
        numeric_cohort: str,
        environment: bytes,
        warmups: int = 3,
        repetitions: int = 10,
        threads: int = 1,
        simd: bool = True,
    ) -> bytes: ...

@final
class ResolvedExperimentProfile:
    def __new__(cls) -> Never: ...
    @property
    def canonical_profile(self) -> bytes: ...
    @property
    def configuration_digest(self) -> str: ...
    @property
    def model(self) -> str: ...

@final
class GatedMultiplyQ7Region:
    def __new__(cls) -> Never: ...
    @property
    def digest(self) -> str: ...
    @property
    def multiply_operation_id(self) -> str: ...
    @property
    def method_component_id(self) -> str: ...
    @property
    def schedule_component_id(self) -> str: ...
    @property
    def max_tensor_elements(self) -> int: ...
    def prepare_material(self) -> GarbledGatedMultiplyQ7Material: ...
    def prepare_evaluator(self, payload: bytes) -> GatedMultiplyQ7Evaluator: ...

@final
class GarbledGatedMultiplyQ7Material:
    def __new__(cls) -> Never: ...
    @property
    def evaluator_payload(self) -> bytes: ...
    @property
    def element_count(self) -> int: ...
    def cancel(self) -> bool: ...
    def encode_gate(self, value: int) -> bytes: ...
    def encode_up(self, value: int) -> bytes: ...
    def decode(self, label: bytes) -> int: ...
    def encode_gates(self, values: object) -> tuple[bytes, ...]: ...
    def encode_ups(self, values: object) -> tuple[bytes, ...]: ...
    def decode_tensor(self, labels: object) -> list[int]: ...

@final
class GatedMultiplyQ7Evaluator:
    def __new__(cls) -> Never: ...
    def evaluate(self, gate_label: bytes, up_label: bytes) -> bytes: ...
    def evaluate_tensor(
        self, gate_labels: object, up_labels: object
    ) -> tuple[bytes, ...]: ...

class Executor:
    def __init__(self, threads: int = 1, simd: bool = True) -> None: ...
    @property
    def threads(self) -> int: ...
    @property
    def simd(self) -> bool: ...
    def modular(self, matrix: Matrix, input: bytes, batch: int, modulus: int) -> bytes: ...
    def wrap32(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def wrap64(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def clear(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def coefficients(self, matrix: Matrix, input: bytes, columns: int, modulus: int) -> bytes: ...

def capabilities() -> dict[str, Any]: ...
def compile_plan(document: bytes) -> CompiledPlan: ...
def resolve_experiment(document: bytes) -> ResolvedExperimentProfile: ...
def assurance_report() -> bytes: ...
def assurance_results() -> bytes: ...
def lower_model(
    config: bytes,
    batch: int,
    max_input_tokens: int,
    max_new_tokens: int,
) -> bytes: ...
def decoder_coverage(plan: bytes, profile: str) -> bytes: ...
def lower_gated_multiply_q7(
    plan: bytes,
    mode: str,
    method_component_id: str = "pllm/r03-crt/v1",
    schedule_component_id: str = "pllm/scalar/v1",
    max_tensor_elements: int = 1,
) -> list[GatedMultiplyQ7Region]: ...
def apply_model_component(plan: bytes, component: bytes) -> bytes: ...
def deployment_benchmark_report(document: bytes) -> bytes: ...
def pack_unsigned(input: bytes, width: int) -> bytes: ...
def unpack_unsigned(input: bytes, width: int) -> bytes: ...
def mask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def unmask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def quantize(input: bytes, rows: int, cols: int, bits: int = 4, scales: bytes | None = None) -> tuple[bytes, bytes]: ...
def uniform_residues(modulus: int, count: int) -> bytes: ...
