from typing import Any

class Matrix:
    def __init__(self, data: bytes, rows: int, cols: int) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def weight_bytes(self) -> int: ...

class Executor:
    def __init__(self, threads: int = 1, simd: bool = True) -> None: ...
    @property
    def threads(self) -> int: ...
    @property
    def simd(self) -> bool: ...
    def modular(self, matrix: Matrix, input: bytes, batch: int, modulus: int) -> bytes: ...
    def wrap32(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def clear(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def coefficients(self, matrix: Matrix, input: bytes, columns: int, modulus: int) -> bytes: ...

def capabilities() -> dict[str, Any]: ...
def pack_unsigned(input: bytes, width: int) -> bytes: ...
def unpack_unsigned(input: bytes, width: int) -> bytes: ...
def mask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def unmask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def quantize(input: bytes, rows: int, cols: int, bits: int = 4, scales: bytes | None = None) -> tuple[bytes, bytes]: ...
def uniform_residues(modulus: int, count: int) -> bytes: ...
