from typing import Any, Never, final

def public_bitplanes(data: bytes, inverse: bool) -> bytes: ...
def public_entropy_encode(data: bytes) -> bytes: ...
def public_entropy_decode(data: bytes, expected_size: int) -> bytes: ...
def public_hadamard(data: bytes, columns: int, block: int, seed: int) -> bytes: ...
def projected_reshare_reference(weights: bytes, a: bytes, b: bytes, before: bool) -> tuple[bytes, int, int]: ...
def prepared_pack_correction(wr: bytes, mask: bytes, widths: bytes, rows: int) -> bytes: ...
def prepared_pack_output(wx: bytes, correction: bytes, widths: bytes, rows: int) -> bytes: ...
def prepared_unpack_output(payload: bytes, mask: bytes, widths: bytes, rows: int) -> bytes: ...
def unpack_residue_rows(payload: bytes, widths: bytes, rows: int) -> bytes: ...
def prepared_mask_input(x: bytes, r: bytes, bits: int) -> bytes: ...
def prepared_center_output(y: bytes, s: bytes, bits: int) -> bytes: ...

def offset_seeded_share(seed: bytes, context: bytes, count: int, bits: int, input: bytes | None = None) -> bytes: ...
def offset_row_bits(weights: bytes, columns: int, max_input: int) -> bytes: ...
def offset_pack_rows(values: bytes, widths: bytes, rows: int) -> bytes: ...
def offset_reconstruct_rows(a: bytes, b: bytes, widths: bytes, rows: int) -> bytes: ...

class PrivatePageServer:
    def evaluate_batch(self, queries: list[bytes]) -> list[bytes]: ...
    def __init__(self, data: bytes, record_bytes: int, party: int) -> None: ...
    def descriptor(self) -> tuple[bytes, int, int]: ...
    def evaluate(self, query: bytes) -> bytes: ...
    def cancel(self, query: bytes) -> None: ...

class HeadRetrievalIndex:
    def __init__(self, rows: int, features: int, rank: int, weights: bytes, projection: bytes, profiles: bytes) -> None: ...
    @property
    def payload_bytes(self) -> int: ...
    def candidates(self, input: bytes, scale: float, count: int) -> tuple[bytes, float]: ...

class PagedMatrix:
    def __init__(self, path: str, artifact_digest: str, threads: int, simd: bool) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def artifact_bytes(self) -> int: ...
    @property
    def metadata_bytes(self) -> int: ...
    @property
    def transient_weight_bytes(self) -> int: ...
    @property
    def weight_digest(self) -> str: ...
    def clear(self, data: bytes, batch: int) -> bytes: ...
    def modular(self, data: bytes, batch: int, modulus: int | None = None) -> bytes: ...
    def gather(self, data: bytes) -> bytes: ...
    def close(self) -> None: ...

def export_paged_weights(path: str, data: bytes, rows: int, cols: int, page_rows: int, compressed: bool) -> str: ...

class PrivatePageDecoder:
    def decode(self, a: bytes, b: bytes) -> bytes: ...
    def cancel(self) -> None: ...

def private_page_issue(digest: bytes, records: int, record_bytes: int, index: int) -> tuple[bytes, bytes, PrivatePageDecoder]: ...

def public_polynomial_shift_witness(
    ring_bits: int, linear: int, masked_gate: int, masked_up: int,
    coefficient_gu: int, coefficient_g2: int,
) -> str: ...

def projected_polynomial_probe(
    layout: str, ring_bits: int, rows: int, hidden: int, channels: int, outputs: int,
    gate: bytes, up: bytes, down: bytes, input: bytes, binding: bytes,
) -> tuple[bytes, str]: ...

def projected_polynomial_estimate(
    mode: str, ring_bits: int, rows: int, hidden: int, channels: int, outputs: int,
) -> str: ...

@final
class CompactQ7Reference:
    def __new__(cls) -> Never: ...
    @property
    def digest(self) -> bytes: ...
    @property
    def calibration_digest(self) -> bytes: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def requested_pieces(self) -> int: ...
    @property
    def pieces(self) -> list[tuple[int, int, list[int]]]: ...
    @property
    def weighted_error(self) -> tuple[int, int]: ...
    @property
    def maximum_encoded_error(self) -> int: ...
    def evaluate(self, value: int) -> int: ...

def fit_compact_silu_q7_reference(
    public_calibration_counts: bytes, max_pieces: int
) -> CompactQ7Reference: ...

@final
class ScaledSiluQ7Reference:
    def __new__(cls) -> Never: ...
    @property
    def max_abs(self) -> int: ...
    @property
    def digest(self) -> bytes: ...
    @property
    def maximum_absolute_error_bound(self) -> float: ...

def create_logrow_scaled_silu_q7_reference(max_abs: int) -> ScaledSiluQ7Reference: ...

@final
class LogRowQ7TensorReference:
    def __new__(cls) -> Never: ...
    @property
    def elements(self) -> int: ...
    @property
    def evaluator_material_bytes(self) -> int: ...
    @property
    def binding_digest(self) -> str: ...
    def evaluate(self, values: bytes) -> bytes: ...
    def evaluate_float32(self, values: bytes) -> bytes: ...

@final
class LogRowQ7SessionReference:
    def __new__(cls) -> Never: ...
    @property
    def issuance_digest(self) -> str: ...
    @property
    def remaining_tensors(self) -> int: ...
    def estimate(self) -> bytes: ...
    def bind_decoder(self, plan_digest: str, max_decode_steps: int) -> None: ...
    def evaluate_float32(
        self, mode: str, decode_step: int, operation_id: str, values: bytes
    ) -> bytes: ...
    def abort(self) -> None: ...

def prepare_logrow_q7_tensor_reference(
    plan: bytes,
    mode: str,
    operation_id: str,
    profile: CompactQ7Reference,
    max_elements: int,
    max_evaluator_material_bytes: int,
) -> LogRowQ7TensorReference: ...
def estimate_logrow_q7_session_reference(
    plan: bytes,
    profile: CompactQ7Reference | ScaledSiluQ7Reference,
    max_elements: int,
    max_evaluator_material_bytes: int,
    max_decode_steps: int,
    max_session_evaluator_material_bytes: int,
) -> bytes: ...
def prepare_logrow_q7_session_reference(
    plan: bytes,
    profile: CompactQ7Reference | ScaledSiluQ7Reference,
    max_elements: int,
    max_evaluator_material_bytes: int,
    max_decode_steps: int,
    max_session_evaluator_material_bytes: int,
) -> LogRowQ7SessionReference: ...

class Matrix:
    def __init__(self, data: bytes, rows: int, cols: int) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def weight_bytes(self) -> int: ...

@final
class CompiledPlan:
    def __new__(cls) -> Never: ...
    @property
    def logical_plan(self) -> bytes: ...
    @property
    def execution_plan(self) -> bytes: ...
    @property
    def plan_lock(self) -> bytes: ...
    @property
    def region_program(self) -> bytes: ...
    @property
    def configuration_digest(self) -> str: ...
    @property
    def logical_plan_digest(self) -> str: ...
    @property
    def execution_plan_digest(self) -> str: ...
    @property
    def plan_lock_digest(self) -> str: ...
    @property
    def input_shape(self) -> tuple[int, ...]: ...
    @property
    def output_shape(self) -> tuple[int, ...]: ...
    def execute_wrap32(
        self,
        weights: bytes,
        input: bytes,
        threads: int = 1,
        simd: bool = True,
    ) -> bytes: ...
    def benchmark_wrap32(
        self,
        weights: bytes,
        input: bytes,
        benchmark_id: str,
        privacy_cohort: str,
        numeric_cohort: str,
        environment: bytes,
        warmups: int = 3,
        repetitions: int = 10,
        threads: int = 1,
        simd: bool = True,
    ) -> bytes: ...

@final
class ResolvedExperimentComposition:
    def __new__(cls) -> Never: ...
    @property
    def canonical_composition(self) -> bytes: ...
    @property
    def composition_digest(self) -> str: ...
    @property
    def configuration_digest(self) -> str: ...
    @property
    def model(self) -> str: ...

@final
class GatedMultiplyQ7Region:
    def __new__(cls) -> Never: ...
    @property
    def digest(self) -> str: ...
    @property
    def multiply_operation_id(self) -> str: ...
    @property
    def method_component_id(self) -> str: ...
    @property
    def schedule_component_id(self) -> str: ...
    @property
    def max_tensor_elements(self) -> int: ...
    def prepare_material(self) -> GarbledGatedMultiplyQ7Material: ...
    def prepare_evaluator(self, payload: bytes) -> GatedMultiplyQ7Evaluator: ...

@final
class GarbledGatedMultiplyQ7Material:
    def __new__(cls) -> Never: ...
    @property
    def evaluator_payload(self) -> bytes: ...
    @property
    def element_count(self) -> int: ...
    def cancel(self) -> bool: ...
    def encode_gate(self, value: int) -> bytes: ...
    def encode_up(self, value: int) -> bytes: ...
    def decode(self, label: bytes) -> int: ...
    def encode_gates(self, values: object) -> tuple[bytes, ...]: ...
    def encode_ups(self, values: object) -> tuple[bytes, ...]: ...
    def decode_tensor(self, labels: object) -> list[int]: ...

@final
class GatedMultiplyQ7Evaluator:
    def __new__(cls) -> Never: ...
    def evaluate(self, gate_label: bytes, up_label: bytes) -> bytes: ...
    def evaluate_tensor(self, gate_labels: object, up_labels: object) -> tuple[bytes, ...]: ...

@final
class FreivaldsPolicy:
    def __init__(
        self,
        target_failure_bits: int,
        max_attempts: int,
        max_matrix_elements: int,
        max_projection_elements: int,
        max_challenge_elements: int,
        max_output_elements: int,
        max_multiply_accumulates: int,
        max_batch_rows: int,
        session_id: bytes,
        register_session: bool,
    ) -> None: ...
    @property
    def checks(self) -> int: ...
    @property
    def target_failure_bits(self) -> int: ...
    @property
    def max_attempts(self) -> int: ...
    @property
    def conservative_failure_bits(self) -> int: ...

@final
class FreivaldsProjectionInventory:
    @property
    def material_id(self) -> bytes: ...
    def __new__(cls) -> Never: ...
    @property
    def inventory_rows(self) -> int: ...
    @property
    def in_features(self) -> int: ...
    @property
    def out_features(self) -> int: ...
    @property
    def checks(self) -> int: ...
    @property
    def max_row_l1(self) -> int: ...
    def payload(self) -> bytes: ...
    def authentication_tag(self, root_seed: bytes) -> bytes: ...
    def claim(
        self,
        root_seed: bytes,
        binding: bytes,
        row_start: int,
        batch_rows: int,
    ) -> FreivaldsVerifier: ...
    def cancel(self) -> bool: ...

@final
class FreivaldsVerifier:
    def __new__(cls) -> Never: ...
    def verify(self, input: bytes, output: bytes) -> bytes: ...
    def cancel(self) -> bool: ...

class Executor:
    def __init__(self, threads: int = 1, simd: bool = True) -> None: ...
    @property
    def threads(self) -> int: ...
    @property
    def simd(self) -> bool: ...
    def modular(self, matrix: Matrix, input: bytes, batch: int, modulus: int) -> bytes: ...
    def wrap32(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def wrap64(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def clear(self, matrix: Matrix, input: bytes, batch: int) -> bytes: ...
    def coefficients(self, matrix: Matrix, input: bytes, columns: int, modulus: int) -> bytes: ...

def capabilities() -> dict[str, Any]: ...
def compile_plan(document: bytes) -> CompiledPlan: ...
def resolve_experiment(document: bytes) -> ResolvedExperimentComposition: ...
def assurance_report() -> bytes: ...
def assurance_results() -> bytes: ...
def lower_model(
    config: bytes,
    batch: int,
    max_input_tokens: int,
    max_new_tokens: int,
) -> bytes: ...
def decoder_coverage(plan: bytes, composition: bytes | None = ...) -> bytes: ...
def decoder_runtime_schedule(plan: bytes, composition: bytes) -> tuple[bytes, str]: ...
def lower_gated_multiply_q7(
    plan: bytes,
    mode: str,
    method_component_id: str = "pllm/r03-crt/v1",
    schedule_component_id: str = "pllm/scalar/v1",
    max_tensor_elements: int = 1,
) -> list[GatedMultiplyQ7Region]: ...
def apply_model_component(plan: bytes, component: bytes) -> bytes: ...
def deployment_benchmark_report(document: bytes) -> bytes: ...
def pack_unsigned(input: bytes, width: int) -> bytes: ...
def unpack_unsigned(input: bytes, width: int) -> bytes: ...
def mask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def unmask(input: bytes, masks: bytes, modulus: int) -> bytes: ...
def quantize(
    input: bytes, rows: int, cols: int, bits: int = 4, scales: bytes | None = None
) -> tuple[bytes, bytes]: ...
def uniform_residues(modulus: int, count: int) -> bytes: ...
def prepare_freivalds(
    weights: bytes,
    out_features: int,
    in_features: int,
    inventory_rows: int,
    root_seed: bytes,
    binding: bytes,
    material_id: bytes,
    signed_input_bound: int,
    signed_output_bound: int,
    policy: FreivaldsPolicy,
) -> FreivaldsProjectionInventory: ...
def import_freivalds(
    payload: bytes,
    authentication_tag: bytes,
    root_seed: bytes,
    inventory_rows: int,
    in_features: int,
    out_features: int,
    binding: bytes,
    material_id: bytes,
    signed_input_bound: int,
    signed_output_bound: int,
    max_row_l1: int,
    policy: FreivaldsPolicy,
) -> FreivaldsProjectionInventory: ...
class _OutputMask:
    def apply(self, value: bytes) -> bytes: ...

class _OutputRelay:
    def combine(self, own: bytes, peer: bytes) -> bytes: ...

class _OutputReceiver:
    def finish(self, frame: bytes) -> bytes: ...

def output_aggregation_issue(context: bytes, widths: bytes, rows: int) -> tuple[_OutputMask, _OutputRelay, _OutputReceiver]: ...

class _IntegerRowMemo:
    def __init__(self, weights: bytes, rows: int, columns: int, maximum: int, threads: int = 1) -> None: ...
    def evaluate(self, input: bytes, rows: int) -> bytes: ...
    def stats(self) -> tuple[int, int, int, int]: ...
    def clear(self) -> None: ...

class _ProgressiveHead:
    def __init__(self, weights: bytes, scales: list[float], columns: int) -> None: ...
    def query(self, input: bytes, scale: float, bits: int) -> tuple[int, list[tuple[int, int, int]]]: ...
    def residual_table(self, bits: int) -> bytes: ...
