from pathlib import Path
from typing import Any, Mapping, Self

class ConfigurationError(ValueError): ...

class ComponentDescriptor:
    component: str
    provider: str
    distribution: str
    version: str
    category: str
    category_version: str
    lifecycle_phase: str
    parameter_schema: Mapping[str, Any]
    capabilities: tuple[str, ...]
    required_host_features: tuple[str, ...]
    role_eligibility: tuple[str, ...]
    artifacts: tuple[Mapping[str, Any], ...]
    evidence: tuple[Mapping[str, Any], ...]
    def to_dict(self) -> dict[str, Any]: ...

class Model:
    source: str
    def __init__(self, source: str) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...

class ComponentRef:
    component: str
    params: Mapping[str, Any]
    def __init__(self, component: str, params: Mapping[str, Any] | None = None) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...

class Cpu(ComponentRef):
    def __init__(self, *, threads: int = 1) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ModelAwareCorrections(ComponentRef):
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class MaskedLinear(ComponentRef):
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class KvCacheEviction(ComponentRef):
    def __init__(
        self,
        *,
        implementation: str = "pllm/mpcache/v1",
        observation_window: tuple[int, int] = (1, 5),
        static_keep: tuple[int, int] = (3, 10),
        dynamic_keep: tuple[int, int] = (1, 4),
        alpha: tuple[int, int] = (3, 5),
        cluster_sizes: tuple[int, ...] = (32, 16),
        share_adjacent_layers: bool = True,
    ) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class BinaryTableGatedMultiplyQ7(ComponentRef):
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class R03CrtGatedMultiplyQ7(ComponentRef):
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ScalarProtectedTensorSchedule(ComponentRef):
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class IndependentLanesProtectedTensorSchedule(ComponentRef):
    def __init__(self, *, max_elements: int = 4) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ChunkedIndependentLanesProtectedTensorSchedule(ComponentRef):
    def __init__(self, *, max_elements: int) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Pipeline:
    profile: str
    model: Model
    components: Mapping[str, ComponentRef]
    def __init__(
        self, profile: str, model: Model, components: Mapping[str, ComponentRef]
    ) -> None: ...
    @classmethod
    def from_profile(
        cls, profile: str, *, model: Model, components: Mapping[str, ComponentRef]
    ) -> Self: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...

class Deployment:
    kind: str
    root: str
    def __init__(self, kind: str, root: str) -> None: ...
    @classmethod
    def local(cls, *, root: str) -> Self: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...

class ExecutionBudget:
    requests: int
    max_input_tokens: int
    max_new_tokens: int
    def __init__(self, requests: int, max_input_tokens: int, max_new_tokens: int) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...

class Experiment:
    name: str
    pipeline: Pipeline
    deployment: Deployment
    budget: ExecutionBudget
    def __init__(
        self, name: str, pipeline: Pipeline, deployment: Deployment, budget: ExecutionBudget
    ) -> None: ...
    @classmethod
    def from_spec(cls, spec: Mapping[str, Any]) -> Self: ...
    @classmethod
    def from_file(cls, path: str | Path) -> Self: ...
    def get_params(self, deep: bool = True) -> dict[str, Any]: ...
    def with_params(self, **changes: object) -> Self: ...
    def to_spec(self) -> dict[str, Any]: ...
    def canonical_bytes(self) -> bytes: ...
    def configuration_digest(self) -> str: ...
    def resolve(self) -> ExperimentProfile: ...

class ExperimentProfile:
    model: str
    canonical_profile: bytes
    configuration_digest: str
    def __init__(self, experiment: Experiment) -> None: ...

def loads_configuration(text: str, *, format: str | None = None) -> Experiment: ...
def load_configuration(path: str | Path) -> Experiment: ...
def canonical_bytes(configuration: Experiment | Mapping[str, Any]) -> bytes: ...
def configuration_digest(configuration: Experiment | Mapping[str, Any]) -> str: ...
