from typing import Never, final

from pllm import _native

@final
class CompiledPlan:
    def __new__(cls) -> Never: ...
    @property
    def logical_plan(self) -> bytes: ...
    @property
    def execution_plan(self) -> bytes: ...
    @property
    def plan_lock(self) -> bytes: ...
    @property
    def region_program(self) -> bytes: ...
    @property
    def configuration_digest(self) -> str: ...
    @property
    def logical_plan_digest(self) -> str: ...
    @property
    def execution_plan_digest(self) -> str: ...
    @property
    def plan_lock_digest(self) -> str: ...
    @property
    def input_shape(self) -> tuple[int, ...]: ...
    @property
    def output_shape(self) -> tuple[int, ...]: ...

def _wrap(native: _native.CompiledPlan) -> CompiledPlan: ...
def _unwrap(plan: CompiledPlan) -> _native.CompiledPlan: ...
