from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.runtime.preparation_server import create_preparation_app as create_preparation_app
from pllm.components._planned import PendingComponent as PendingMethod

class PreparationProvider(ComponentRef): ...

class ModelAwareCorrections(PreparationProvider):
    descriptor: ComponentDescriptor
    def __init__(self, *, storage: str = ...) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class PreparedInventory(ComponentRef):
    descriptor: ComponentDescriptor
    def __init__(self, policy: str = ..., *, rows: int | None = ..., refill: str | None = ..., stage_window: int = ..., allocation: str = ...) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, object]: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class BFVCorrelations(PreparationProvider):
    descriptor: ComponentDescriptor
    def __init__(self, *, poly_modulus_degree: int = 4096) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class HEAuthenticatedPreprocessing(PreparationProvider):
    descriptor: ComponentDescriptor
    def __init__(
        self,
        *,
        poly_modulus_degree: int = 4096,
        threads: int = 1,
        enable_linear_correlations: bool = True,
    ) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class MaverickRaaPreprocessing(PendingMethod): ...
class CarnivalPublicMaskSampling(PendingMethod): ...
