#!/usr/bin/env python3
"""Generate documentation inventories from PLLM's public Python and CLI surfaces."""

from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PYTHON_ROOT = ROOT / "python"
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

GENERATED_NOTICE = "Generated by `scripts/generate_developer_reference.py`; do not edit."
CLI_REFERENCE_ROOT = ROOT / "docs/content/docs/reference/cli"
CLI_ROOT_ORDER = ("gateway", "serve", "config", "components", "benchmark", "dev")
CLI_EXAMPLES = {
    "pllm gateway": "pllm gateway --config client.toml",
    "pllm serve inference": "pllm serve inference --config inference.json",
    "pllm serve preparation": "pllm serve preparation --config preparation.json",
    "pllm config show": "pllm config show examples/pllm.yaml",
    "pllm config export": ("pllm config export examples/pllm.yaml --output experiment.json"),
    "pllm components list": "pllm components list --format json",
    "pllm components show": "pllm components show pllm/cpu --format json",
    "pllm benchmark run": (
        "pllm benchmark run --prompt-file prompt.txt --max-output-tokens 24 "
        "--repetitions 3 --output benchmark.json"
    ),
    "pllm dev dashboard": "pllm dev dashboard --tiny",
}
PUBLIC_MODULES = (
    "pllm",
    "pllm.config",
    "pllm.models",
    "pllm.plan",
    "pllm.components",
    "pllm.correlation",
    "pllm.kernels",
    "pllm.nonlinear",
    "pllm.passes",
    "pllm.profiles",
    "pllm.providers",
    "pllm.protocols",
    "pllm.protocols.masked_linear",
    "pllm.preparation",
    "pllm.roles",
    "pllm.schedulers",
    "pllm.sources",
    "pllm.state",
    "pllm.verification",
    "pllm.pipeline",
    "pllm.deployment",
    "pllm.runtime",
    "pllm.compiler",
    "pllm.evidence",
)


def _frontmatter(title: str, description: str) -> str:
    return (
        "---\n"
        f"title: {json.dumps(title)}\n"
        f"description: {json.dumps(description)}\n"
        "---\n\n"
        f"> {GENERATED_NOTICE}\n\n"
    )


def _cell(value: object) -> str:
    if value is None or value == "" or value == [] or value == () or value == {}:
        return "not recorded"
    if isinstance(value, str):
        return value.replace("|", "\\|").replace("\n", " ")
    rendered = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "`" + rendered.replace("|", "\\|") + "`"


def _code(value: str) -> str:
    return "`" + value.replace("|", "\\|") + "`"


def _walk_parsers(
    parser: argparse.ArgumentParser,
) -> list[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    found: list[tuple[tuple[str, ...], argparse.ArgumentParser]] = [((), parser)]
    pending: list[tuple[tuple[str, ...], argparse.ArgumentParser]] = [((), parser)]
    while pending:
        prefix, current = pending.pop(0)
        for action in current._actions:
            choices = getattr(action, "choices", None)
            if not isinstance(choices, dict):
                continue
            for name, child in choices.items():
                item = (prefix + (name,), child)
                found.append(item)
                pending.append(item)
    return found


def cli_help_sections() -> tuple[tuple[str, str], ...]:
    from pllm._cli.app import build_parser

    sections = []
    for path, parser in _walk_parsers(build_parser()):
        command = "pllm" + (f" {' '.join(path)}" if path else "")
        sections.append((command, parser.format_help()))
    return tuple(sections)


def cli_leaf_commands(
    sections: tuple[tuple[str, str], ...] | None = None,
) -> tuple[str, ...]:
    sections = sections or cli_help_sections()
    parent_commands = {command.rsplit(" ", 1)[0] for command, _ in sections if " " in command}
    return tuple(
        command for command, _ in sections if command != "pllm" and command not in parent_commands
    )


def validate_cli_examples(sections: tuple[tuple[str, str], ...] | None = None) -> None:
    leaves = set(cli_leaf_commands(sections))
    examples = set(CLI_EXAMPLES)
    if leaves == examples:
        return
    missing = ", ".join(sorted(leaves - examples)) or "none"
    extras = ", ".join(sorted(examples - leaves)) or "none"
    raise ValueError(
        f"CLI examples must match parser leaves exactly; missing: {missing}; extras: {extras}"
    )


def render_cli_help() -> str:
    sections = [f"# {GENERATED_NOTICE}\n"]
    for command, help_text in cli_help_sections():
        sections.extend((f"\n$ {command} --help\n", help_text))
    return "".join(sections)


def render_cli_reference(
    sections: tuple[tuple[str, str], ...] | None = None,
) -> str:
    sections = sections or cli_help_sections()
    leaves = cli_leaf_commands(sections)
    body = [
        _frontmatter(
            "CLI reference",
            "Exact commands, arguments, and help text from the installed PLLM CLI.",
        ),
        "Use the CLI to run private inference, operate provider roles, benchmark the real "
        "transport, inspect configuration, and compare components. Open "
        "[Private inference](/cli/private-inference/), [Provider roles](/cli/provider-roles/), "
        "[Benchmarking](/cli/benchmarking/), or "
        "[Inspect components](/cli/inspect-and-research/). Choose a command group below for "
        "exact generated arguments.\n\n",
        "## Complete grammar\n\n",
        "```text\n",
        *[f"{command} [OPTIONS]\n" for command in leaves],
        "```\n\n",
        "Global options accepted at each parser level are `--format {human,json,jsonl}`, `--quiet`, "
        "`--no-color`, `--no-input`, and `--dry-run`. Root also accepts `--version`. Argument "
        "abbreviation is disabled.\n\n",
        "[Download exact complete help](/downloads/cli-help.txt).\n\n",
        "## `pllm --help`\n\n",
        "```text\n",
        sections[0][1],
        "```\n",
    ]
    return "".join(body)


def render_cli_command_reference(command: str, help_text: str, example: str | None) -> str:
    body = [_frontmatter(command, f"Exact {command} help from the installed PLLM CLI.")]
    if example is None:
        body.append(
            "Choose a subcommand below. Each executable command page includes an example.\n\n"
        )
    else:
        if command == "pllm dev dashboard":
            body.append("This dashboard is a development-only local tool.\n\n")
        body.extend(("## Example\n\n", "```bash\n", example, "\n```\n\n"))
    body.extend(("## Options\n\n", "```text\n", help_text, "```\n"))
    return "".join(body)


def _render_meta(title: str, pages: tuple[str, ...], *, root: bool = False) -> str:
    metadata: dict[str, object] = {"title": title}
    if root:
        metadata["root"] = True
    metadata["pages"] = pages
    return json.dumps(metadata, indent=2) + "\n"


def render_cli_reference_outputs() -> dict[Path, str]:
    sections = cli_help_sections()
    validate_cli_examples(sections)
    leaf_commands = set(cli_leaf_commands(sections))
    commands = [
        (tuple(command.split()[1:]), command, help_text) for command, help_text in sections[1:]
    ]
    parent_paths = {path[:depth] for path, _, _ in commands for depth in range(1, len(path))}
    outputs = {
        CLI_REFERENCE_ROOT / "index.mdx": render_cli_reference(sections),
        CLI_REFERENCE_ROOT / "meta.json": _render_meta(
            "Command reference", ("index", *CLI_ROOT_ORDER), root=True
        ),
    }
    for path, command, help_text in commands:
        source = (
            CLI_REFERENCE_ROOT.joinpath(*path, "index.mdx")
            if path in parent_paths
            else CLI_REFERENCE_ROOT.joinpath(*path[:-1], f"{path[-1]}.mdx")
        )
        outputs[source] = render_cli_command_reference(
            command, help_text, CLI_EXAMPLES[command] if command in leaf_commands else None
        )
    for parent in sorted(parent_paths):
        children = tuple(
            path[-1]
            for path, _, _ in commands
            if len(path) == len(parent) + 1 and path[:-1] == parent
        )
        outputs[CLI_REFERENCE_ROOT.joinpath(*parent, "meta.json")] = _render_meta(
            parent[-1].replace("-", " ").title(), ("index", *children)
        )
    return outputs


def public_exports() -> tuple[dict[str, Any], ...]:
    exports: list[dict[str, Any]] = []
    for module_name in PUBLIC_MODULES:
        module = importlib.import_module(module_name)
        names = tuple(getattr(module, "__all__", ()))
        for name in sorted(names):
            value = getattr(module, name)
            exports.append({"module": module_name, "name": name, "value": value})
    return tuple(exports)


def _signature(value: object) -> str:
    if not callable(value):
        return type(value).__name__
    try:
        return str(inspect.signature(value))
    except (TypeError, ValueError):
        return "signature not exposed"


def _stub_path(module_name: str) -> Path | None:
    relative = Path(*module_name.split("."))
    candidates = (
        PYTHON_ROOT / relative.with_suffix(".pyi"),
        PYTHON_ROOT / relative / "__init__.pyi",
    )
    return next((path for path in candidates if path.is_file()), None)


def _stub_node(
    module_name: str, name: str, seen: frozenset[tuple[str, str]] = frozenset()
) -> ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef | None:
    key = (module_name, name)
    if key in seen:
        return None
    path = _stub_path(module_name)
    if path is None:
        return None
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if (
            isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == name
        ):
            return node
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                if (alias.asname or alias.name) == name:
                    return _stub_node(node.module, alias.name, seen | {key})
    return None


def _function_declaration(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    decorators = {
        decorator.id for decorator in node.decorator_list if isinstance(decorator, ast.Name)
    }
    if "property" in decorators:
        annotation = ast.unparse(node.returns) if node.returns is not None else "Any"
        return f"property {node.name}: {annotation}"
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    if "classmethod" in decorators:
        prefix += "classmethod "
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    return f"{prefix}{node.name}({ast.unparse(node.args)}){returns}"


def _typed_details(exports: list[str], value: object) -> tuple[str, tuple[str, ...]]:
    node = None
    for export in exports:
        module_name, name = export.rsplit(".", 1)
        node = _stub_node(module_name, name)
        if node is not None:
            break
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return _function_declaration(node), ()
    if isinstance(node, ast.ClassDef):
        members = []
        for child in node.body:
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if child.name.startswith("_") and child.name not in {"__init__", "__new__"}:
                    continue
                members.append(_function_declaration(child))
            elif isinstance(child, ast.AnnAssign) and isinstance(child.target, ast.Name):
                members.append(f"{child.target.id}: {ast.unparse(child.annotation)}")
        constructor = next(
            (item for item in members if item.startswith("__new__") or item.startswith("__init__")),
            "constructor not exposed",
        )
        if "-> Never" in constructor:
            constructor = "not publicly constructible"
        return constructor, tuple(members)
    if inspect.isclass(value):
        members = []
        for name, member in value.__dict__.items():
            if name.startswith("_"):
                continue
            if isinstance(member, property):
                annotation = (
                    inspect.Signature.empty
                    if member.fget is None
                    else inspect.signature(member.fget).return_annotation
                )
                rendered = (
                    "Any"
                    if annotation is inspect.Signature.empty
                    else inspect.formatannotation(annotation)
                )
                members.append(f"property {name}: {rendered}")
            elif isinstance(member, classmethod):
                members.append(f"classmethod {name}{_signature(member.__func__)}")
            elif callable(member):
                members.append(f"{name}{_signature(member)}")
        return _signature(value), tuple(sorted(members))
    return _signature(value), ()


def api_inventory() -> tuple[dict[str, Any], ...]:
    grouped: dict[int, dict[str, Any]] = {}
    for export in public_exports():
        value = export["value"]
        record = grouped.setdefault(
            id(value),
            {
                "canonical": f"{getattr(value, '__module__', export['module'])}."
                f"{getattr(value, '__qualname__', export['name'])}",
                "kind": "class"
                if inspect.isclass(value)
                else "function"
                if callable(value)
                else type(value).__name__,
                "signature": _signature(value),
                "exports": [],
                "value": value,
            },
        )
        record["exports"].append(f"{export['module']}.{export['name']}")
    for record in grouped.values():
        record["exports"].sort()
        record["signature"], record["members"] = _typed_details(record["exports"], record["value"])
        del record["value"]
    return tuple(sorted(grouped.values(), key=lambda item: (item["canonical"], item["exports"])))


def render_python_reference() -> str:
    exports = public_exports()
    by_module: dict[str, list[str]] = {name: [] for name in PUBLIC_MODULES}
    for export in exports:
        by_module[export["module"]].append(f"{export['module']}.{export['name']}")
    body = [
        _frontmatter(
            "Python API inventory",
            "Public Python classes, functions, and evidence APIs in the installed package.",
        ),
        "One row describes each Python object. `Exports` lists facade aliases, preventing duplicate "
        "handwritten class definitions. Presence is API inventory only; consult "
        "[status](/sdk/reference/status/) for coverage and maturity.\n\n",
        "## Python SDK example\n\n",
        "```python\n",
        "import pllm\n",
        "from pllm.config import Experiment\n\n",
        "assert pllm.Experiment is Experiment\n",
        "```\n\n",
        "API: [`pllm.Experiment`](/sdk/reference/python/pllm/#objects-and-signatures)\n\n",
        "## Facades\n\n",
    ]
    for module, names in by_module.items():
        body.append(
            f"- `{module}`: {', '.join(f'`{name}`' for name in names) if names else 'no public exports recorded'}\n"
        )
    body.extend(
        (
            "\n## Objects and signatures\n\n",
            "| Canonical object | Kind | Signature/type | Public members | Exports |\n",
            "| --- | --- | --- | --- | --- |\n",
        )
    )
    for item in api_inventory():
        exports_text = ", ".join(_code(name) for name in item["exports"])
        members_text = "; ".join(_code(name) for name in item["members"]) or "not recorded"
        body.append(
            f"| {_code(item['canonical'])} | {item['kind']} | {_code(item['signature'])} | {members_text} | {exports_text} |\n"
        )
    return "".join(body)


def component_catalog() -> tuple[dict[str, Any], ...]:
    from pllm.components import list_components

    return tuple(component.to_dict() for component in list_components())


def render_component_catalog() -> str:
    body = [
        _frontmatter(
            "Component catalog",
            "Built-in component records with implementation, coverage, and evidence status.",
        ),
        "Catalog reflects `pllm.components.list_components()` only. Empty descriptor evidence is shown "
        "as no applicable evidence; it is not a pass.\n\n",
        "## Python SDK example\n\n",
        "```python\n",
        "from pllm.components import get, get_component\n\n",
        'component_class = get("pllm/cpu")\n',
        'component = get_component("pllm/cpu")\n',
        'assert component_class.describe() is component\n',
        'assert "cpu" in component.capabilities\n',
        "```\n\n",
        "API: [`pllm.components.get`](/sdk/reference/python/pllm/#objects-and-signatures)\n\n",
        "| Identity/version | Lifecycle | Implementation maturity | Provenance | Input/output representation | Roles/topology | Privacy/assurance | Model/operator coverage | Evidence/cohort | Known limitations |\n",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    ]
    for item in component_catalog():
        evidence = _cell(item["evidence"]) if item["evidence"] else "no applicable evidence"
        coverage = f"capabilities: {_cell(item['capabilities'])}; host features: {_cell(item['required_host_features'])}"
        body.append(
            "| "
            + " | ".join(
                (
                    f"{_code(item['component'])} / {_code(item['version'])}",
                    _cell(item["lifecycle_phase"]),
                    "not recorded",
                    f"provider {_code(item['provider'])}; distribution {_code(item['distribution'])}; source links not recorded",
                    "not recorded",
                    _cell(item["role_eligibility"]),
                    "assurance status not recorded; privacy status not recorded",
                    coverage,
                    evidence,
                    "not recorded",
                )
            )
            + " |\n"
        )
    return "".join(body)


def render_outputs() -> dict[Path, str]:
    outputs = render_cli_reference_outputs()
    outputs.update(
        {
            ROOT / "docs/content/docs/reference/python/pllm/index.mdx": render_python_reference(),
            ROOT / "docs/content/docs/reference/components.mdx": render_component_catalog(),
            ROOT / "docs/public/downloads/cli-help.txt": render_cli_help(),
        }
    )
    return outputs


def generate(*, check: bool = False) -> int:
    stale = []
    for path, content in render_outputs().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        if check:
            print("Generated developer reference is stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"Generated {len(stale)} developer reference files.")
    else:
        print("Generated developer reference is current.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed output differs")
    return generate(check=parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
