#!/usr/bin/env python3
"""Generate documentation inventories from PLLM's public Python and CLI surfaces."""

from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PYTHON_ROOT = ROOT / "python"
if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))

GENERATED_NOTICE = "Generated by `scripts/generate_developer_reference.py`; do not edit."
PUBLIC_MODULES = (
    "pllm",
    "pllm.config",
    "pllm.models",
    "pllm.plan",
    "pllm.components",
    "pllm.kernels",
    "pllm.protocols",
    "pllm.protocols.masked_linear",
    "pllm.preparation",
    "pllm.pipeline",
    "pllm.deployment",
    "pllm.runtime",
    "pllm.research",
    "pllm.compiler",
    "pllm.evidence",
)


def _frontmatter(title: str, description: str) -> str:
    return (
        "---\n"
        f"title: {json.dumps(title)}\n"
        f"description: {json.dumps(description)}\n"
        "---\n\n"
        f"> {GENERATED_NOTICE}\n\n"
    )


def _cell(value: object) -> str:
    if value is None or value == "" or value == [] or value == () or value == {}:
        return "not recorded"
    if isinstance(value, str):
        return value.replace("|", "\\|").replace("\n", " ")
    rendered = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "`" + rendered.replace("|", "\\|") + "`"


def _code(value: str) -> str:
    return "`" + value.replace("|", "\\|") + "`"


def _walk_parsers(parser: argparse.ArgumentParser) -> list[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    found: list[tuple[tuple[str, ...], argparse.ArgumentParser]] = [((), parser)]
    pending: list[tuple[tuple[str, ...], argparse.ArgumentParser]] = [((), parser)]
    while pending:
        prefix, current = pending.pop(0)
        for action in current._actions:
            choices = getattr(action, "choices", None)
            if not isinstance(choices, dict):
                continue
            for name, child in choices.items():
                item = (prefix + (name,), child)
                found.append(item)
                pending.append(item)
    return found


def cli_help_sections() -> tuple[tuple[str, str], ...]:
    from pllm._cli.app import build_parser

    sections = []
    for path, parser in _walk_parsers(build_parser()):
        command = "pllm" + (f" {' '.join(path)}" if path else "")
        sections.append((command, parser.format_help()))
    return tuple(sections)


def render_cli_help() -> str:
    sections = [f"# {GENERATED_NOTICE}\n"]
    for command, help_text in cli_help_sections():
        sections.extend((f"\n$ {command} --help\n", help_text))
    return "".join(sections)


def render_cli_reference() -> str:
    sections = cli_help_sections()
    leaves = []
    parent_commands = {command.rsplit(" ", 1)[0] for command, _ in sections if " " in command}
    for command, _ in sections:
        if command not in parent_commands and command != "pllm":
            leaves.append(command)
    body = [
        _frontmatter(
            "CLI reference",
            "Exact commands, arguments, and help text from the installed PLLM CLI.",
        ),
        "Available commands inspect metadata or run local development tools. See "
        "[compatibility and status](/sdk/reference/status/) for unavailable lifecycle commands.\n\n",
        "## Complete grammar\n\n",
        "```text\n",
        *[f"{command} [OPTIONS]\n" for command in leaves],
        "```\n\n",
        "Global options accepted at each parser level are `--format {human,json,jsonl}`, `--quiet`, "
        "`--no-color`, `--no-input`, and `--dry-run`. Root also accepts `--version`. Argument "
        "abbreviation is disabled.\n\n",
        "[Download exact complete help](/downloads/cli-help.txt).\n\n",
    ]
    for command, help_text in sections:
        body.extend((f"## `{command}`\n\n", "```text\n", help_text.rstrip(), "\n```\n\n"))
    return "".join(body)


def public_exports() -> tuple[dict[str, Any], ...]:
    exports: list[dict[str, Any]] = []
    for module_name in PUBLIC_MODULES:
        module = importlib.import_module(module_name)
        names = tuple(getattr(module, "__all__", ()))
        for name in sorted(names):
            value = getattr(module, name)
            exports.append({"module": module_name, "name": name, "value": value})
    return tuple(exports)


def _signature(value: object) -> str:
    if not callable(value):
        return type(value).__name__
    try:
        return str(inspect.signature(value))
    except (TypeError, ValueError):
        return "signature not exposed"


def _stub_path(module_name: str) -> Path | None:
    relative = Path(*module_name.split("."))
    candidates = (PYTHON_ROOT / relative.with_suffix(".pyi"), PYTHON_ROOT / relative / "__init__.pyi")
    return next((path for path in candidates if path.is_file()), None)


def _stub_node(
    module_name: str, name: str, seen: frozenset[tuple[str, str]] = frozenset()
) -> ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef | None:
    key = (module_name, name)
    if key in seen:
        return None
    path = _stub_path(module_name)
    if path is None:
        return None
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            return node
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                if (alias.asname or alias.name) == name:
                    return _stub_node(node.module, alias.name, seen | {key})
    return None


def _function_declaration(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    return f"{prefix}{node.name}({ast.unparse(node.args)}){returns}"


def _typed_details(exports: list[str], value: object) -> tuple[str, tuple[str, ...]]:
    node = None
    for export in exports:
        module_name, name = export.rsplit(".", 1)
        node = _stub_node(module_name, name)
        if node is not None:
            break
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return _function_declaration(node), ()
    if isinstance(node, ast.ClassDef):
        members = []
        for child in node.body:
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if child.name.startswith("_") and child.name not in {"__init__", "__new__"}:
                    continue
                members.append(_function_declaration(child))
            elif isinstance(child, ast.AnnAssign) and isinstance(child.target, ast.Name):
                members.append(f"{child.target.id}: {ast.unparse(child.annotation)}")
        constructor = next(
            (item for item in members if item.startswith("__new__") or item.startswith("__init__")),
            "constructor not exposed",
        )
        if "-> Never" in constructor:
            constructor = "not publicly constructible"
        return constructor, tuple(members)
    if inspect.isclass(value):
        members = []
        for name, member in value.__dict__.items():
            if name.startswith("_"):
                continue
            target = member.fget if isinstance(member, property) else member
            if callable(target):
                members.append(f"{name}{_signature(target)}")
        return _signature(value), tuple(sorted(members))
    return _signature(value), ()


def api_inventory() -> tuple[dict[str, Any], ...]:
    grouped: dict[int, dict[str, Any]] = {}
    for export in public_exports():
        value = export["value"]
        record = grouped.setdefault(
            id(value),
            {
                "canonical": f"{getattr(value, '__module__', export['module'])}."
                f"{getattr(value, '__qualname__', export['name'])}",
                "kind": "class" if inspect.isclass(value) else "function" if callable(value) else type(value).__name__,
                "signature": _signature(value),
                "exports": [],
                "value": value,
            },
        )
        record["exports"].append(f"{export['module']}.{export['name']}")
    for record in grouped.values():
        record["exports"].sort()
        record["signature"], record["members"] = _typed_details(record["exports"], record["value"])
        del record["value"]
    return tuple(sorted(grouped.values(), key=lambda item: (item["canonical"], item["exports"])))


def render_python_reference() -> str:
    exports = public_exports()
    by_module: dict[str, list[str]] = {name: [] for name in PUBLIC_MODULES}
    for export in exports:
        by_module[export["module"]].append(f"{export['module']}.{export['name']}")
    body = [
        _frontmatter(
            "Python API inventory",
            "Public Python classes, functions, and evidence APIs in the installed package.",
        ),
        "One row describes each Python object. `Exports` lists facade aliases, preventing duplicate "
        "handwritten class definitions. Presence is API inventory only; consult "
        "[status](/sdk/reference/status/) for coverage and maturity.\n\n",
        "## Python SDK example\n\n",
        "```python\n",
        "from pllm.components import list_components\n\n",
        "print([component.component for component in list_components()])\n",
        "```\n\n",
        "## Facades\n\n",
    ]
    for module, names in by_module.items():
        body.append(f"- `{module}`: {', '.join(f'`{name}`' for name in names) if names else 'no public exports recorded'}\n")
    body.extend(("\n## Objects and signatures\n\n", "| Canonical object | Kind | Signature/type | Public members | Exports |\n", "| --- | --- | --- | --- | --- |\n"))
    for item in api_inventory():
        exports_text = ", ".join(_code(name) for name in item["exports"])
        members_text = "; ".join(_code(name) for name in item["members"]) or "not recorded"
        body.append(
            f"| {_code(item['canonical'])} | {item['kind']} | {_code(item['signature'])} | {members_text} | {exports_text} |\n"
        )
    return "".join(body)


def component_catalog() -> tuple[dict[str, Any], ...]:
    from pllm.components import list_components

    return tuple(component.to_dict() for component in list_components())


def render_component_catalog() -> str:
    body = [
        _frontmatter(
            "Component catalog",
            "Built-in component records with implementation, coverage, and evidence status.",
        ),
        "Catalog reflects `pllm.components.list_components()` only. Empty descriptor evidence is shown "
        "as no applicable evidence; it is not a pass.\n\n",
        "## Python SDK example\n\n",
        "```python\n",
        "from pllm.components import get_component\n\n",
        "component = get_component(\"pllm/cpu\")\n",
        "print(component.to_dict())\n",
        "```\n\n",
        "| Identity/version | Lifecycle | Implementation maturity | Provenance | Input/output representation | Roles/topology | Privacy/assurance | Model/operator coverage | Evidence/cohort | Known limitations |\n",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    ]
    for item in component_catalog():
        evidence = _cell(item["evidence"]) if item["evidence"] else "no applicable evidence"
        coverage = f"capabilities: {_cell(item['capabilities'])}; host features: {_cell(item['required_host_features'])}"
        body.append(
            "| "
            + " | ".join(
                (
                    f"{_code(item['component'])} / {_code(item['version'])}",
                    _cell(item["lifecycle_phase"]),
                    "not recorded",
                    f"provider {_code(item['provider'])}; distribution {_code(item['distribution'])}; source links not recorded",
                    "not recorded",
                    _cell(item["role_eligibility"]),
                    "assurance status not recorded; privacy status not recorded",
                    coverage,
                    evidence,
                    "not recorded",
                )
            )
            + " |\n"
        )
    return "".join(body)


def research_catalog() -> dict[str, tuple[dict[str, Any], ...]]:
    from pllm.research import list_methods, list_recipes, list_sources

    return {
        "sources": tuple(record.to_dict() for record in list_sources()),
        "methods": tuple(record.to_dict() for record in list_methods()),
        "recipes": tuple(record.to_dict() for record in list_recipes()),
    }


def _research_header() -> list[str]:
    return [
        "| Identity/version | Lifecycle phase | Implementation maturity | Source/provenance | Input/output representation | Roles/topology | Privacy/assurance | Model/operator coverage | Evidence/cohort | Known limitations |\n",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    ]


def render_research_catalog() -> str:
    catalog = research_catalog()
    body = [
        _frontmatter(
            "Research catalog",
            "Generated source, method, and read-only composition recipe inventory from pllm.research.",
        ),
        "These records are read-only metadata. Source acquisition, implementation, fidelity, runtime "
        "coverage, benchmark evidence, assurance, and publication eligibility remain independent.\n\n",
        "## Sources\n\n",
        *_research_header(),
    ]
    for item in catalog["sources"]:
        link = f"[{_cell(item.get('title'))}]({item['primary_url']}); digest {_code(item.get('paper_digest', 'not recorded'))}"
        body.append(
            "| "
            + " | ".join(
                (
                    f"{_code(item['id'])} / {_code(item['schema_version'])}",
                    f"source access: {_cell(item.get('access'))}",
                    "not recorded",
                    link,
                    "not recorded",
                    "not recorded",
                    "no applicable evidence",
                    "not recorded",
                    "no applicable evidence",
                    _cell(item.get("notes")),
                )
            )
            + " |\n"
        )
    body.extend(("\n## Method implementations\n\n", *_research_header()))
    for item in catalog["methods"]:
        lifecycle = item.get("lifecycle_status", {})
        body.append(
            "| "
            + " | ".join(
                (
                    f"{_code(item['id'])} / {_code(item.get('version', item['schema_version']))}",
                    _cell(lifecycle),
                    _cell(item.get("implementation_status")),
                    f"sources: {_cell(item.get('source_record_ids'))}; upstream locks: {_cell(item.get('upstream_artifact_lock_ids'))}",
                    f"input {_cell(item.get('input_representations'))}; output {_cell(item.get('output_representations'))}",
                    f"online {_cell(item.get('online_roles'))}; preparation {_cell(item.get('preparation_phase'))}",
                    f"assurance {_cell(lifecycle.get('assurance'))}; obligations {_cell(item.get('assurance_obligations'))}",
                    f"profiles {_cell(item.get('eligible_profiles'))}; protected execution {_cell(lifecycle.get('protected_execution'))}",
                    f"benchmark {_cell(lifecycle.get('benchmark'))}; cohort not recorded",
                    _cell(item.get("semantic_scope")),
                )
            )
            + " |\n"
        )
    body.extend(("\n## Compositions and recipes\n\n", *_research_header()))
    for item in catalog["recipes"]:
        identity = item.get("id", item["registry_alias"])
        provenance = item.get("source_record_id") or item.get("primary_url")
        evidence = "required but not produced" if item.get("workflow_status") == "not_executed" else _cell(item.get("required_evidence"))
        body.append(
            "| "
            + " | ".join(
                (
                    f"{_code(identity)} / {_code(item['schema_version'])}",
                    f"acquisition {_cell(item.get('source_acquisition_status'))}; workflow {_cell(item.get('workflow_status'))}",
                    "not recorded",
                    _cell(provenance),
                    "not recorded",
                    "not recorded",
                    "assurance status not recorded; privacy status not recorded",
                    f"model not recorded; operator targets {_cell(item.get('target_modules'))}",
                    f"{evidence}; cohort not recorded",
                    _cell(item.get("failure_policy")),
                )
            )
            + " |\n"
        )
    return "".join(body)


def render_outputs() -> dict[Path, str]:
    return {
        ROOT / "docs/content/docs/reference/cli/index.mdx": render_cli_reference(),
        ROOT / "docs/content/docs/reference/python/pllm/index.mdx": render_python_reference(),
        ROOT / "docs/content/docs/reference/components.mdx": render_component_catalog(),
        ROOT / "docs/content/docs/reference/research.mdx": render_research_catalog(),
        ROOT / "docs/public/downloads/cli-help.txt": render_cli_help(),
    }


def generate(*, check: bool = False) -> int:
    stale = []
    for path, content in render_outputs().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        if check:
            print("Generated developer reference is stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"Generated {len(stale)} developer reference files.")
    else:
        print("Generated developer reference is current.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed output differs")
    return generate(check=parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
