from pllm.configuration import ComponentDescriptor, ComponentRef

class ProtectedScheduler(ComponentRef): ...

class ScalarProtectedTensorSchedule(ProtectedScheduler):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class IndependentLanesProtectedTensorSchedule(ProtectedScheduler):
    descriptor: ComponentDescriptor
    def __init__(self, *, max_elements: int = 4) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ChunkedIndependentLanesProtectedTensorSchedule(ProtectedScheduler):
    descriptor: ComponentDescriptor
    def __init__(self, *, max_elements: int) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
