from pllm.protocols.base import ProtocolMethod as ProtocolMethod
from pllm.protocols.masked_linear import MaskedLinear as MaskedLinear
from pllm.protocols.runtime_arms import BlindedLinear as BlindedLinear
from pllm.protocols.runtime_arms import CleartextLinear as CleartextLinear
from pllm.protocols.runtime_arms import DirectFHE as DirectFHE
from pllm.protocols.runtime_arms import GuardedLinear as GuardedLinear
from pllm.protocols.runtime_arms import SecureLinear as SecureLinear
from pllm.components._planned import PendingComponent as PendingMethod
from typing import Literal
from pllm._native import CompactQ7Reference, LogRowQ7SessionReference, LogRowQ7TensorReference
from pllm.modeling import ModelPlan

class LogRowQ7SessionEstimate:
    plan_digest: str
    profile_digest: bytes
    max_decode_steps: int
    prefill_elements: int
    decode_elements_per_step: int
    reserved_evaluator_material_bytes: int
    largest_tensor_material_bytes: int
    estimate_digest: str
    def __init__(
        self,
        plan_digest: str,
        profile_digest: bytes,
        max_decode_steps: int,
        prefill_elements: int,
        decode_elements_per_step: int,
        reserved_evaluator_material_bytes: int,
        largest_tensor_material_bytes: int,
        estimate_digest: str,
    ) -> None: ...

def estimate_logrow_q7_session_reference(
    plan: ModelPlan,
    profile: CompactQ7Reference,
    *,
    max_elements: int,
    max_evaluator_material_bytes: int,
    max_decode_steps: int,
    max_session_evaluator_material_bytes: int,
) -> LogRowQ7SessionEstimate: ...
def prepare_logrow_q7_session_reference(
    plan: ModelPlan,
    profile: CompactQ7Reference,
    *,
    max_elements: int,
    max_evaluator_material_bytes: int,
    max_decode_steps: int,
    max_session_evaluator_material_bytes: int,
) -> LogRowQ7SessionReference: ...
def prepare_logrow_q7_tensor_reference(
    plan: ModelPlan,
    profile: CompactQ7Reference,
    *,
    mode: Literal["prefill", "decode"],
    operation_id: str,
    max_elements: int,
    max_evaluator_material_bytes: int,
) -> LogRowQ7TensorReference: ...

class ProjectiveLabelConversion(PendingMethod): ...
class MosaicMaskedGpuOutsourcing(PendingMethod): ...
class MaverickDelegatedLinear(PendingMethod): ...
class EncryptedSparseVectorCompression(PendingMethod): ...
class OpenWeightVerifiableOutsourcing(PendingMethod): ...
class BatchedIntervalLookup(PendingMethod): ...
class BumblebeeTwoPartyTransformer(PendingMethod): ...
class DashPreparedArithmeticGarbling(PendingMethod): ...
class SecretDualCodeMatVec(PendingMethod): ...
class MoaiNoninteractiveTransformer(PendingMethod): ...
class NexusNoninteractiveTransformer(PendingMethod): ...
class TrapdooredMatrixDelegation(PendingMethod): ...
class ActiveFssProtocol(PendingMethod): ...
class ThorHomomorphicTransformer(PendingMethod): ...
class BoltHybridTransformer(PendingMethod): ...
class PrivateEmbeddingLookup(PendingMethod): ...
class LogRowGarbledLookup(PendingMethod): ...
class NimbusTwoPartyTransformer(PendingMethod): ...
class OrcaFssGpuExecution(PendingMethod): ...
class SigmaFssDecoder(PendingMethod): ...
class CipherGptPrivateTokenSelection(PendingMethod): ...
class FlutePrivateLookup(PendingMethod): ...
class GrottoRingDpfProtocol(PendingMethod): ...
class PumaThreePartyDecoder(PendingMethod): ...
class PrimerHomomorphicTransformer(PendingMethod): ...
class CheetahTwoPartyNeural(PendingMethod): ...
class IronTwoPartyTransformer(PendingMethod): ...
class PikaRingFssProtocol(PendingMethod): ...
class TheXHomomorphicTransformer(PendingMethod): ...
class Aby2ArithmeticBooleanConversion(PendingMethod): ...
class FssMixedFixedPointConversion(PendingMethod): ...
class CryptFlowTwoPartyNeural(PendingMethod): ...
class MixedArithmeticEdabitConversion(PendingMethod): ...
class SilentNiscCircuitSetup(PendingMethod): ...
class GarbledNeuralProtocol(PendingMethod): ...
class FssOfflinePreprocessing(PendingMethod): ...
class GazelleHybridHeGarbling(PendingMethod): ...
class CryptoNetsHomomorphicNeural(PendingMethod): ...
class ExtendedFssKeys(PendingMethod): ...
class CrtGarblingGadgetProtocol(PendingMethod): ...
class FunctionSecretSharingKeys(PendingMethod): ...
class HalfGatesCircuit(PendingMethod): ...
class ProtectedDecisionProgram(PendingMethod): ...
