from pllm.configuration import ComponentDescriptor, ComponentRef

class ClientBundleTransport(ComponentRef):
    descriptor: ComponentDescriptor
    def __init__(self, encoding: str = ...) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, object]: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
