from collections.abc import Sequence
import numpy as np
from pllm.configuration import ComponentDescriptor, ComponentRef

class Metric(ComponentRef): ...

class Latency(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, statistic: str = "median", phase: str = "online") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Throughput(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, basis: str = "tokens") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Communication(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, direction: str = "total", phase: str = "online") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Memory(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, kind: str = "peak_rss") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Energy(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, source: str = "not_available") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Accuracy(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, dataset: str, measure: str = "task_score") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Perplexity(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, dataset: str) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ReferenceAgreement(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, dataset_digest: str, reference_checkpoint_digest: str, top_k: int = 5) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

def measure_reference_agreement(
    candidate_logits: Sequence[float] | np.ndarray,
    reference_logits: Sequence[float] | np.ndarray,
    *,
    top_k: int = 5,
) -> dict[str, float]: ...

class Cost(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, currency: str = "USD", basis: str = "request") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
