from pllm.configuration import ComponentDescriptor, ComponentRef

class Metric(ComponentRef): ...

class Latency(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, statistic: str = "median", phase: str = "online") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Throughput(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, basis: str = "tokens") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Communication(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, direction: str = "total", phase: str = "online") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Memory(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, kind: str = "peak_rss") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Energy(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, source: str = "not_available") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Accuracy(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, dataset: str, measure: str = "task_score") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Perplexity(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, dataset: str) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class Cost(Metric):
    descriptor: ComponentDescriptor
    def __init__(self, *, currency: str = "USD", basis: str = "request") -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
