from pllm.configuration import ComponentDescriptor, ComponentRef
from pllm.roles.topology import (
    Channel as Channel,
    Role as Role,
    RoleGraph as RoleGraph,
    client_only_reference_graph as client_only_reference_graph,
    two_online_reference_graph as two_online_reference_graph,
)

class InferenceRole(ComponentRef): ...

class Inference(InferenceRole):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class RoleTopology(ComponentRef): ...

class PreparedProviderRoles(RoleTopology):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ClientOnlyRoles(RoleTopology):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class TwoOnlineOffsetRoles(RoleTopology):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class OutputHeadAtInference(ComponentRef):
    descriptor: ComponentDescriptor
    def __init__(self) -> None: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ClientPlacement(ComponentRef):
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ClientLinearRoles(ClientPlacement):
    roles: tuple[str, ...]
    descriptor: ComponentDescriptor
    def __init__(self, roles: tuple[str, ...] | list[str]) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, object]: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...

class ClientPrefixLayers(ClientPlacement):
    layers: int
    descriptor: ComponentDescriptor
    def __init__(self, layers: int) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, int]: ...
    @classmethod
    def describe(cls) -> ComponentDescriptor: ...
